debug: false
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/webflash?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: webflash
    password: webflash190602@ABC
  jpa:
    hibernate:
      ddl-auto: update
